INSERT INTO vocabularies (word, meaning, pronunciation, topic) VALUES
('cat', 'con mèo', '/kæt/', 'animal'),
('dog', 'con chó', '/dɔːg/', 'animal'),
('lion', 'sư tử', '/ˈlaɪ.ən/', 'animal'),
('bird', 'con chim', '/bɜːrd/', 'animal'),
('travel', 'du lịch', '/ˈtræv.əl/', 'travel'),
('ticket', 'vé', '/ˈtɪk.ɪt/', 'travel'),
('passport', 'hộ chiếu', '/ˈpɑːs.pɔːrt/', 'travel'),
('luggage', 'hành lý', '/ˈlʌɡ.ɪdʒ/', 'travel'),
('office', 'văn phòng', '/ˈɔː.fɪs/', 'work'),
('manager', 'quản lý', '/ˈmæn.ɪ.dʒər/', 'work'),
('meeting', 'cuộc họp', '/ˈmiː.tɪŋ/', 'work'),
('teacher', 'giáo viên', '/ˈtiː.tʃər/', 'school'),
('student', 'học sinh', '/ˈstuː.dənt/', 'school'),
('classroom', 'lớp học', '/ˈklæs.ruːm/', 'school'),
('homework', 'bài tập về nhà', '/ˈhoʊm.wɝːk/', 'school'),
('lesson', 'bài học', '/ˈles.ən/', 'school'),
('notebook', 'quyển vở', '/ˈnoʊt.bʊk/', 'school'),
('library', 'thư viện', '/ˈlaɪ.brer.i/', 'school'),
('exam', 'kỳ thi', '/ɪɡˈzæm/', 'school'),
('rice', 'cơm', '/raɪs/', 'food'),
('bread', 'bánh mì', '/bred/', 'food'),
('milk', 'sữa', '/mɪlk/', 'food'),
('apple', 'táo', '/ˈæp.əl/', 'food'),
('noodles', 'mì', '/ˈnuː.dəlz/', 'food'),
('soup', 'súp', '/suːp/', 'food'),
('salad', 'sa lát', '/ˈsæl.əd/', 'food'),
('juice', 'nước ép', '/dʒuːs/', 'food'),
('breakfast', 'bữa sáng', '/ˈbrek.fəst/', 'food'),
('restaurant', 'nhà hàng', '/ˈres.tər.ɑːnt/', 'food'),
('father', 'bố', '/ˈfɑː.ðər/', 'family'),
('mother', 'mẹ', '/ˈmʌð.ər/', 'family'),
('brother', 'anh em trai', '/ˈbrʌð.ər/', 'family'),
('sister', 'chị em gái', '/ˈsɪs.tər/', 'family'),
('grandfather', 'ông', '/ˈɡræn.fɑː.ðər/', 'family'),
('grandmother', 'bà', '/ˈɡræn.mʌð.ər/', 'family'),
('uncle', 'chú cậu', '/ˈʌŋ.kəl/', 'family'),
('aunt', 'cô dì', '/ænt/', 'family'),
('song', 'bài hát', '/sɔːŋ/', 'music'),
('music', 'âm nhạc', '/ˈmjuː.zɪk/', 'music'),
('guitar', 'đàn guitar', '/ɡɪˈtɑːr/', 'music'),
('piano', 'đàn piano', '/piˈæn.oʊ/', 'music'),
('drum', 'trống', '/drʌm/', 'music'),
('singer', 'ca sĩ', '/ˈsɪŋ.ər/', 'music'),
('concert', 'buổi hòa nhạc', '/ˈkɑːn.sɚt/', 'music'),
('headphones', 'tai nghe', '/ˈhed.foʊnz/', 'music');

INSERT INTO topic_image_configs (topic, keywords) VALUES
('animal', 'animal, pet, cute, portrait'),
('family', 'family, parent, mother, father, home'),
('school', 'student, study, classroom, books, desk'),
('travel', 'travel, passport, suitcase, luggage, road'),
('work', 'office, work, business, desk, meeting'),
('food', 'food, meal, dish, plate, kitchen'),
('music', 'music, guitar, piano, singer, concert')
ON CONFLICT (topic) DO UPDATE SET keywords = EXCLUDED.keywords;
